export const GET_SEARCHED_HOSPITALS = "GET_SEARCHED_HOSPITALS";
export const CLEAR_HOSPITALS_SEARCHED = "CLEAR_HOSPITALS_SEARCHED";
export const CATEGORIES_FILTER = "CATEGORIES_FILTER";
export const HOSPITAL_TYPES_FILTER = "HOSPITAL_TYPES_FILTER";
export const ADDONS_FILTER = "ADDONS_FILTER";
export const CLEAR_FILTERS_ONLY = "CLEAR_FILTERS_ONLY";