export const GET_SEARCHED_DOCTORS = "GET_SEARCHED_DOCTORS";
export const CLEAR_DOCTORS_SEARCHED = "CLEAR_DOCTORS_SEARCHED";
export const SPECIALITIES_FILTER = "SPECIALITIES_FILTER";
export const HOSPITAL_TYPES_FILTER = "HOSPITAL_TYPES_FILTER";
export const LANGUAGE_FILTER = "LANGUAGE_FILTER";
export const NATIONALITIES_FILTER = "NATIONALITIES_FILTER";
export const GENDERS_FILTER = "GENDERS_FILTER";
export const CLEAR_FILTERS_ONLY = "CLEAR_FILTERS_ONLY";