export const GET_INSURANCES = "GET_INSURANCES";
export const DELETE_INSURANCE = "DELETE_INSURANCE";
export const ADD_INSURANCE = "ADD_INSURANCE";
export const GET_PAGINATED_INSURANCES = "GET_PAGINATED_INSURANCES";
export const UPDATE_INSURANCE = "UPDATE_INSURANCE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
