export const GET_NURSES = "GET_NURSES";
export const ADD_NURSE = "ADD_NURSE";
export const DELETE_NURSE = "DELETE_NURSE";

export const SEARCH_NURSE = "SEARCH_NURSE";
export const SET_NURSE_PAGE_NUMBER = "SET_NURSE_PAGE_NUMBER";
export const CLEAR_NURSE_SEARCH_RESULTS = "CLEAR_NURSE_SEARCH_RESULTS";