export const GET_PATIENTS = "GET_PATIENTS";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SELECT_PATIENT = "SELECT_PATIENT";
export const ADD_PATIENT_BY_NURSE = "ADD_PATIENT_BY_NURSE";
export const UPDATE_VITALS = "UPDATE_VITALS";

export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";