export const GET_LAB_REQUESTS = "GET_LAB_REQUESTS";
export const DELETE_REQUEST = "DELETE_REQUEST";

export const SET_DOCTOR_PENDING_LAB_REQUESTS_PAGE_NUMBER = "SET_DOCTOR_PENDING_LAB_REQUESTS_PAGE_NUMBER";