export const GET_SPECIALITIES = "GET_SPECIALITIES";
export const DELETE_SPECIALITY = "DELETE_SPECIALITY";
export const ADD_SPECIALITY = "ADD_SPECIALITY";
export const GET_PAGINATED_SPECIALITIES = "GET_PAGINATED_SPECIALITIES";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";